/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class trikita_obsqr_QrDecoder */

#ifndef _Included_trikita_obsqr_QrDecoder
#define _Included_trikita_obsqr_QrDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     trikita_obsqr_QrDecoder
 * Method:    decode
 * Signature: (II[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_trikita_obsqr_QrDecoder_decode
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
